version: '3.3'

services:
  mongo:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: Elliot
      MONGO_INITDB_ROOT_PASSWORD: NubeElPequeñoMundo
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data:/data/db
